org: slsplus
app: admin-system
stage: dev

component: egg
name: admin-system-backend

inputs:
  region: ${env:REGION}
  src:
    src: ./
    exclude:
      - '.git/**'
      - 'docs/**'
      - 'test/**'
      - 'node_modules/**'
  functionName: serverless-admin-system
  runtime: Nodejs10.15
  layers:
    - name: ${output:${stage}:${app}:${name}-layer.name}
      version: ${output:${stage}:${app}:${name}-layer.version}
  functionConf:
    timeout: 120
    vpcConfig:
      vpcId: ${output:${stage}:${app}:${app}-vpc.vpcId}
      subnetId: ${output:${stage}:${app}:${app}-vpc.subnetId}
    environment:
      variables:
        NODE_ENV: production
        SERVERLESS: true
        DB_HOST: ${output:${stage}:${app}:${app}-db.private.host}
        DB_PORT: ${output:${stage}:${app}:${app}-db.private.port}
        DB_NAME: ${output:${stage}:${app}:${app}-db.private.dbname}
        DB_USER: ${output:${stage}:${app}:${app}-db.private.user}
        DB_PASSWORD: ${output:${stage}:${app}:${app}-db.private.password}
  apigatewayConf:
    environment: release
    protocols:
      - https
